### ISSUE TITLE
Version 2.0.0 Portenta MBED not running on windows fine on linux

### ISSUE THREAD

**Issue by hpssjellis** [arduino/ArduinoCore-mbed#183]
Large Machine Learning Tensorflow Lite program that worked fine on Mbed Core Version 1.3.2. With Version 2.0.0 Portenta only Installation works fine on Linux but does not run on windows. Here is the error message.

```
arm-none-eabi-gcc: error: CreateProcess: No such file or directory


```

This single file (using TensorflowLite as an included library) can be used on a windows machine to demonstrate the problem.

[https://raw.githubusercontent.com/hpssjellis/my-examples-for-the-arduino-portentaH7/master/m09-Tensoflow/b01_makerML_hello_world.ino](https://raw.githubusercontent.com/hpssjellis/my-examples-for-the-arduino-portentaH7/master/m09-Tensoflow/b01_makerML_hello_world.ino)

The file does however work on the deprecated Multiple Mbed Core version 2.0.0

**Comment by facchinm** [comment]
Hi @hpssjellis ,
as a woraround you can open `C:\Users\yourusername\AppData\Local\Arduino15\packages\arduino\hardware\mbed_portenta\2.0.0\variants\PORTENTA_H7_M7\includes.txt` and remove all the lines starting with `-iwithprefixbefore/mbed/connectivity/nanostack/` .
The issue is, as always, the command line length limit on Windows :disappointed: 
I'll be pushing a proper fix and a new core version during this week
