### ISSUE TITLE
Raspberry Pico on macOS

### ISSUE THREAD

**Issue by sstaub** [arduino/ArduinoCore-mbed#189]
macOS 11.2.3
After uploading to the Raspberry Pico board, I get a message that the board is unmounted incorrectly.
This is specific to macOS, it seems that uploading works over mass storage, that cause the problem.

**Comment by facchinm** [comment]
Hi @sstaub ,
the core doesn't use the mass storage interface for uploading but it gets exposed by default; this patch https://github.com/arduino/ArduinoCore-mbed/pull/190/commits/91d896f22701dd1588e6c3b08988049c89acd927 should avoid that so during normal flow the notification won't appear.

**Comment by sstaub** [comment]
@facchinm When did you merge the solution?

**Comment by facchinm** [comment]
I had to revert the patch here https://github.com/arduino/ArduinoCore-mbed/commit/d2942e207a5b71ec564cd1fe9eacf2b6a88de5a2 since it would have broken all Windows "pure" Pico installations (micropython and so on). If there's any Windows drivers guru out there that knows how to handle the situation I'd be glad to turn it back on :slightly_smiling_face:

**Comment by sstaub** [comment]
We need to know which operation system is used, maybe there is a macro for that in gcc.

**Comment by sstaub** [comment]
Ok, I understood. In the moment I need to update manually with every version update.
