### ISSUE TITLE
Unable to upload sketch to raspberry pi pico

### ISSUE THREAD

**Issue by Tejas-Singh-py** [arduino/ArduinoCore-mbed#191]
Hello,
I have just installed Arduino IDE on my raspberry pi 3 to program my pico(RP2040). I opened the blink example but after it compiled it showed an error while uploading (The pico was in bootloader mode). What should I do now. Is it because of the ARM compatibility issue?
**I used the official version, not @earlephilhower 's version*'*
P.S. This is my first time with Arduino IDE. Sorry for (if any) typos.

Youtube:- Tejas Singh YT

**Comment by facchinm** [comment]
Hi @Tejas-Singh-py ,
the problem might be due to missing `udev` rules (we don't use mass storage upload but the other interface exposed by the bootloader). Try running this (https://github.com/arduino/ArduinoCore-mbed/blob/master/post_install.sh) script as root and then retry the upload (disconnecting and reconnectiong the Pico might help).
If this doesn't help, for further debugging please enable verbose upload from File/Preferences and paste here the output, thanks!

**Comment by Tejas-Singh-py** [comment]
Thanks, it worked 
please check out my youtube channel https://www.youtube.com/channel/UCCsEfbaCHPjM0Dhx69TrJPw

**Comment by avielbr** [comment]
@facchinm This worked for me as well to solve the same problem. Thanks!

**Comment by 29chandu** [comment]
@facchinm thanks for the solution

**Comment by Pomax** [comment]
Any way to run this on Windows?
