### ISSUE TITLE
mbed_error_printf prints only first character to USB Serial before crashing

### ISSUE THREAD

**Issue by magnusnordlander** [arduino/ArduinoCore-mbed#274]
When using mbed_error_printf (which is called from any kind of error handling in Mbed OS) to write to USB Serial, only the first character is printed before something crashes. This makes it difficult to debug errors.

### Environment
* Arduino IDE 1.18.3
* Arduino Mbed OS Nano Boards 2.2.0
* Arduino Nano RP2040 Connect

### Example code

```c
#include <mbed.h>

REDIRECT_STDOUT_TO(Serial);

void setup() {
  delay(5000);
  printf("First\n");
  mbed_error_printf("Second\n");
  printf("Third\n");
}

void loop() {

}
```
### Expected results

The following should be written to the USB serial:
```
First
Second
Third

```

### Actual results

The following is written to the USB serial:
```
First
S
```

**Comment by facchinm** [comment]
Hi @magnusnordlander ,
`mbed_error_printf` calls `core_util_critical_section_enter` (https://github.com/ARMmbed/mbed-os/blob/a3be10c976c36da222517abc0cb4f81e88ff8552/platform/source/mbed_board.c#L103) so it can only work if the underlying handler is not based on interrupts (like a real UART).
Please not that your code is not working with cores > 2.0.0 since it's missing a `Serial.begin(baudrate)` before calling any print.
