### ISSUE TITLE
PDM Library - Random Microphone Spikes on Nano RP2040 Connect

### ISSUE THREAD

**Issue by julienmartin84** [arduino/ArduinoCore-mbed#289]
Hello!
I have been playing with the PDM library and the bundled PDM example on an Arduino Nano RP2040 Connect.

**v2.1.0**: no spike artifact
**v2.2.0**: spikes artifacts
**v2.3.1**: spikes artifacts

Screenshot 1: no noise in the room
![](https://aws1.discourse-cdn.com/arduino/original/4X/6/a/d/6ad7ce28063a2beaa6d209adf644b52f3931c074.png)

Screenshot 2: was playing a clean sine wave near the arduino
![](https://aws1.discourse-cdn.com/arduino/original/4X/1/b/9/1b96b4b63118d7e7346d0e869c1e642bcc179859.png)

The spikes seem to disappear when using a frequency of 8kHz or less instead of the 16kHz default of the example.
I describe the problem in details [here](https://forum.arduino.cc/t/nano-rp2040-connect-microphone-spike/881069/12)
In this Arduino forum topic, user Klaus_K identified some change that occurred with 2.2.0 and that could maybe cause the issue.

**Comment by facchinm** [comment]
Hi @julienmartin84 ,
thanks for taking the time to report the issue here.
The glitch is due to the new clock frequency provided to the microphone (starting from https://github.com/arduino/ArduinoCore-mbed/commit/c97ec7e540be9a602b225309229d2a1e3366e937), which is above the nominal maximum at 16khz sampling rate
![image](https://user-images.githubusercontent.com/8843437/128850388-ce9efd16-68c4-4cb0-8a8f-7fd6f38a8fdc.png)
I pushed #302 to fix this, it would be awesome if you could test it and report if it really fixes the issue :wink:

**Comment by julienmartin84** [comment]
It is working correctly after i updated **Arduino Mbed OS Nano Boards**
Thank you!

**Comment by RickorDD** [comment]
I have a problem with my Arduino Connect PR2040 and the internal MIC.
SerialPlotterExample and Edge Impulse runs not with Decimation = 64 only with 128 but there the Spikes.

https://forum.edgeimpulse.com/t/arduino-nano-rp2040-help/4638/22
