### ISSUE TITLE
Does raspberry pico support I2C in slave mode?  

### ISSUE THREAD

**Issue by kharlytoz** [arduino/ArduinoCore-mbed#313]
Hi, 

I am wondering if raspberry pico support I2C in slave mode using Arduino IDE? I did a small test using a raspberry pi 4 and I could detect the I2C address of the pico, but when trying to "poll" information from pico, I do not get anything. Not sure if it is possible to use pico as slave. I am intending to use both I2C port which I already tested as master and worked fine. I want to use one I2C port as master and the other I2C port as slave. Below the test where I can read pico's I2C address but won't receive the "hello". 

![image](https://user-images.githubusercontent.com/50023915/131765747-340bba5a-928d-4e68-8869-3ef0499e0074.png)

```
#include <Wire.h>
MbedI2C MyWire(p20,p21); //(SDA,SCL)

void setup() {
pinMode(LED_BUILTIN, OUTPUT);
Wire.begin();
MyWire.begin();
MyWire.onRequest(requestEvent); 
Serial.begin(9600);
}

void loop() {
 digitalWrite(LED_BUILTIN, HIGH);   
 delay(200);                       
 digitalWrite(LED_BUILTIN, LOW);    
 delay(200);       
 }

void requestEvent() {
  MyWire.write("hello "); // respond with message of 6 bytes
  Serial.println("test"); 
}
```

**Comment by facchinm** [comment]
Hi @kharlytoz,
thr RP2040 mbed-os porting supports I2CSlave and should work just fine on the alternate pins you found.
The issue is `MyWire.begin()` , which initialized the port as master.
By changing to `MyWire.begin(address)` the slave mode will be activated and everything should work as expected.
One more thing, remember to add pullups on I2C lines if they are not already there (internal pullups are usually unsiuitable for high speeds)
