### ISSUE TITLE
Cannot using hardware/i2c.h and hardware/spi.h with Arduino Nano RP2040 Connect

### ISSUE THREAD

**Issue by markub3327** [arduino/ArduinoCore-mbed#459]
Hi,

I need to use a part of Pico SDK with Arduino Nano RP2040 Connect. I cannot use `hardware/i2c.h` and `hardware/spi.h` but both are detected by the compiler. I need to use the Pico's SPI and I2C libraries for DMA purpose.

Thanks.

```cpp
[Starting] Analyzing sketch '3Pi_Robot.ino'
Please see the build logs in output path: /Users/martin/Documents/Projects/3Pi_Robot/build
/Users/martin/Documents/Projects/3Pi_Robot/src/Drivers/Camera/ArduCAM.cpp: In member function 'void ArduCAM::Arducam_init()':
/Users/martin/Documents/Projects/3Pi_Robot/src/Drivers/Camera/ArduCAM.cpp:656:3: error: 'i2c_init' was not declared in this scope
   i2c_init(I2C_PORT, 100 * 1000);
   ^~~~~~~~
/Users/martin/Documents/Projects/3Pi_Robot/src/Drivers/Camera/ArduCAM.cpp:656:3: note: suggested alternative: '_i2c_init'
   i2c_init(I2C_PORT, 100 * 1000);
   ^~~~~~~~
   _i2c_init
/Users/martin/Documents/Projects/3Pi_Robot/src/Drivers/Camera/ArduCAM.cpp:664:3: error: 'spi_init' was not declared in this scope
   spi_init(SPI_PORT, 4 * 1000*1000);
   ^~~~~~~~
/Users/martin/Documents/Projects/3Pi_Robot/src/Drivers/Camera/ArduCAM.cpp:664:3: note: suggested alternative: '_spi_init'
   spi_init(SPI_PORT, 4 * 1000*1000);
   ^~~~~~~~
   _spi_init

Error during build: exit status 1
```

**Comment by facchinm** [comment]
Hi @markub3327 ,
when porting RP2040 to mbed-os we had to rename some functions due to clashing with mbed HAL signatures (https://github.com/ARMmbed/mbed-os/pull/14488/commits/af01b0810416c1be95a8c849787e217b2dc12797#diff-7eb7255c696573984bdb53cf4013617923d148c4ed8206056510bfb4b72d9976 ). I think you can safely use `_spi_init` as suggested by the compiler but I can't assure that it won't clash with other components as if it was a pure pico-sdk build.
