### ISSUE TITLE
No compiler optimization specified.

### ISSUE THREAD

**Issue by WestfW** [arduino/ArduinoCore-mbed#460]
platform.txt is devoid of any optimization options for the various compiler types, meaning that all user, library, and core code is compiled with the default "-O0" optimization level (which is known to be "very poor" for gcc.)

"-Os" should be specified in there somewhere.

This is a problem for both the mbed_rp2040 and mbed_nano "boards", it may apply to others as well.

**Comment by facchinm** [comment]
Hi Bill,
due to the way we wrap mbed buildsystem, the optimization flags are specified in each variant's `cflags.txt` and `cppflags.txt` (like here https://github.com/arduino/ArduinoCore-mbed/blob/master/variants/RASPBERRY_PI_PICO/cxxflags.txt#L6 ).
I understand it's not very convenient if we'd ever want to allow changing this via some tooling but is should not be a bug :wink:
