### ISSUE TITLE
pico_stdio library

### ISSUE THREAD

**Issue by freasy** [arduino/ArduinoCore-mbed#494]
The current included pico-sdk is not up to date and is missing the `pico_stdio` library which is getting referenced by `pico_stdlib`.

**Comment by facchinm** [comment]
Hi @freasy ,
the latest patchset (https://github.com/arduino/ArduinoCore-mbed/commit/4a9d8fe2067d1f51448950ef631b817da541acc1) updates pico-sdk to 1.3.0 and will be generally available in the next version of the core.
About `pico_stdio` and `pico_stdlib`, we don't compile them in since they clash with the functionalities provided by mbed-os.
