### ISSUE TITLE
Custom Variant with RP2040

### ISSUE THREAD

**Issue by sabas1080** [arduino/ArduinoCore-mbed#522]
Hello
I am creating a custom variant for my devboard, the first start is correct but when restarting the program does not start, with the core of https://github.com/earlephilhower/arduino-pico it works correctly

Memory flash: https://www.mouser.mx/ProductDetail/Winbond/W25Q16JVUUIQ-TR?qs=qSfuJ%252Bfl%2Fd7XfZZWV6GUpQ%3D%3D

Thanks

**Comment by facchinm** [comment]
Hi @sabas1080 ,
if it starts correctly on the first run it means that the [second stage bootloader](https://github.com/arduino/mbed-os/blob/extrapatches-6.15.1/targets/TARGET_RASPBERRYPI/TARGET_RP2040/TARGET_RASPBERRY_PI_PICO/bs2_default_padded_checksummed.S) is fine (it would have been the culprit since it's tied to the flash chip).
What do you mean with "restarting the program"? Just press the reset button?

**Comment by sabas1080** [comment]
@facchinm Do you have any possible theory? Thanks

**Comment by sabas1080** [comment]
@facchinm What is the correct procedure/steps to add a variant of RP2040? I think that's where the problem

**Comment by sabas1080** [comment]
@facchinm I have found the error in the crystal

**Comment by sabas1080** [comment]
https://github.com/raspberrypi/pico-sdk/pull/869
