### ISSUE TITLE
QSPIFBlockDevice with Arduino Nano 33 BLE

### ISSUE THREAD

**Issue by MatthewMong** [arduino/ArduinoCore-mbed#646]
I have followed the instructions in #377 to compile mbed for use with a W25Q16JVSSIQ, however when I initiate the QSPIFBlockDevice with the init call I get error -4002, I've checked my wiring and confirmed I have the right pins set in the json file.

**Comment by facchinm** [comment]
Hi @MatthewMong , the issue is likely due to some missing quirk for that particular flash in mbed-os https://github.com/ARMmbed/mbed-os/blob/b3a5d6a473380e78e3db49890082879d0ef6b6a3/storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.cpp#L1068C23-L1068C44 . Sometimes vendor change the way to enable Quad mode so that file should be updated accordingly. Nothing we can do about it in this repo, sorry.
