### ISSUE TITLE
Unclear as to which GPIO pins can be used for PWM on the Arduino Giga R1

### ISSUE THREAD

**Issue by Gerriko** [arduino/ArduinoCore-mbed#708]
I notice in the pinout documentation that only GPIO pins 2 - 13 can be assigned for PWM output on the Giga. Is there scope to increase this number somehow. Please could someone explain what the restrictions are and if there is scope for the user to change this (e.g. recompile the Mbed core etc.)

I cannot remember where I found it, but there was mention of a high speed clock conflict with the Portenta H7. 

In the full pinout diagram there are references to different timers linked to some of the analog pins as well as the can bus pins but there no indication if these can be used for PWM as well using the standard analogWrite method.

Similarly, there are other GPIO pins such as D37 & D38, which are tied to TIM8_CH2 timer, and D48 is tied to TIM1_CH1N/TIM8_CH3 etc.

Thanks

**Comment by facchinm** [comment]
Hi @Gerriko ,
on the Giga we adopted a "safe" approach, so pins 2-13 are **assured** to work as PWMs with no conflict/limitation. All other pins you may find uncommented [here](https://github.com/arduino/mbed-os/blob/extrapatches-6.17.0/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_GIGA/PeripheralPins.c#L154-L261) can be used too, but the user must take extra care since they could be shared with outer pins
