### ISSUE TITLE
Low Power or Mode Sleep Nano BLE or Nano BLE Sense

### ISSUE THREAD

**Issue by sabas1080** [arduino/ArduinoCore-mbed#713]
Hello

I am looking for the best way to put sleep mode on the nano 33 BLE boards 

Thanks

**Comment by facchinm** [comment]
Hi @sabas1080 ,
the RTOS already takes care of calling the low level sleep functions as soon as it has nothing to do (eg. when the user calls `delay()` and there's no other thread running).
Unfortunately, USB and `micros()` timers prevent this to happen automatically, so the user must disable them to achieve the lowest power consumption.
To do so, there are a couple of useful functions:

To stop the micros() timer
```
  //Stop non-lowpower Timer
  ArduinoTimer t = getTimer();
  t.stop();
```

To stop USB
```
#include "usb_phy_api.h"
    get_usb_phy()->deinit();
```

This will allow the deep sleep to kick in. To upload a new sketch, since the USB will be unavailable, you should double tap the reset button to force bootloader mode and restore the ability to load new code.
