### ISSUE TITLE
Timing issue on GIGA on M4

### ISSUE THREAD

**Issue by pedromsousalima** [arduino/ArduinoCore-mbed#726]
It was noticed that the GIGA is inconsistent tracking time across different cores. This was seen on multiple GIGA boards until now we have found no exception.
When using functions like micros() and tracking time on both cores separately a significant discrepancy is noticeable. Specifically, the M7 core seems to be ticking quicker than real-time.
This was not replicable on Portenta boards.

**Comment by facchinm** [comment]
@pedromsousalima I investigated the issue and indeed there's a problem lurking in the M4 "variant sharing".
Basically, all boards with M4 coprocessor share the same variant but GIGA is the only one with a 16Mhz crystal instead than a 25MHz.
This explains the micros() difference, since the timebase is extracted by `HAL_RCC_GetSysClockFreq()` which in fact always returns 25000000.
I'll try to find a workaround that doesn't hurt the whole system.

In the meantime, let me suggest to avoid adding links to internal documentation when posting on public github, since they are useless for people that may want to help in the investigation.

For reference, here's the code to show the issue
```c++
#include "Arduino.h"
#include "SerialRPC.h"

#ifdef CORE_CM4
void setup() {
  SerialRPC.begin(115200);
}

void loop() {
  SerialRPC.println(millis());
  SerialRPC.println(micros());
  delay(1000);
}
#endif

#ifdef CORE_CM7
void setup() {
  Serial.begin(115200);
  SerialRPC.begin();
}

void loop() {
  String data = "";
  while (SerialRPC.available()) {
    data += (char)SerialRPC.read();
  }
  if (data != "") {
    Serial.write(data.c_str(), data.length());
  }
  data = "";
  while (Serial.available()) {
    data += (char)Serial.read();
  }
  if (data != "") {
    SerialRPC.write(data.c_str(), data.length());
  }
}
#endif
```
