### ISSUE TITLE
.begin() for WEP is in Wifi.h but is not implemented in Wifi.cpp.

### ISSUE THREAD

**Issue by K1ttyKat** [arduino/ArduinoCore-mbed#819]
I have been asked to raise an issue here but I have never done this before so forgive any errors in formatting, etc.

I have a Giga R1 and the accompanying display and wanted to get the time from an NTP server.  I therefore followed the official Arduino examples shown here: [https://docs.arduino.cc/tutorials/giga-r1-wifi/giga-wifi](url)

I found that I could make a WPA connection using...

`status = WiFi.begin(ssid, pass);`

...but that when I tried to make a WEP connection by adding the network index number like this:

`status = WiFi.begin(ssid, keyIndex, pass);`

...I got a compilation error.

I raised this on the Arduino Forum here  [https://forum.arduino.cc/t/giga-wifi-not-working/1207373](url) and a helpful person called stevebeswick replied saying that "_the .begin() for WEP is in Wifi.h but is not implemented in Wifi.cpp_" and suggested that I should raise an issue here about it - which I have now done.

I hope this provides all necessary information.

**Comment by facchinm** [comment]
@K1ttyKat what happens if you try to connect to the WEP network using the `WiFi.begin(ssid, pass);` API? The undelying mbed-os WiFi API doesn't handle WEP keys explicitly (https://os.mbed.com/docs/mbed-os/v6.16/apis/wi-fi.html) but it automatically handle the key index.
If it works, I'd add a fake   ` WiFi.begin(ssid, keyIndex, pass);` implementation to the library ignoring the second paramenter.
